name: Generate Doxygen Documentation

on:
  push:
    tags:
      - 'v*'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cod
        uses: actions/checkout@v4

      - name: Debug - Vezi structura folderelor
        run: ls -R

      - name: Instalare Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Executare Doxygen
        run: |
          # Verificăm dacă Doxyfile există înainte de a rula
          # Ajustează calea de mai jos dacă 'ls -R' îți arată altceva!
          cd laboratories/cicd-documentation/
          if [ -f Doxyfile ]; then
            doxygen Doxyfile
          else
            echo "EROARE: Doxyfile nu a fost găsit în laboratories/cicd-documentation/"
            exit 1
          fi

      - name: Salvare Artefact
        uses: actions/upload-artifact@v4
        with:
          name: Doxygen-HTML-Docs
          path: laboratories/cicd-documentation/html/